language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: MLSSXeM10o3MagPNXfNZ5moddigRPpBw7QWmMwH/QyPOY8HOgU/SrvcCWWPAKRp6n912KlEtdiEOwBPpI6sv76Hh/mEaLaHdW9ewJ23h4B2eGZaiVGuRWoQ2ywec2S9f73MUWXPHbSeA92UGL9dCkUt618cJ9VE7S+p7fvmZdVzrkK9xhLxZ8B2zzd2rxdPKvwDokYjT/yOCJWQvekLkfWIgytqXgaOVolOXdAlEjmGjiYxHWEntTgCKCMNhPBIxVyGPhR0/av7ui44ysgMIJwsQ/N+L4/Moh2bVfnJJZns89M90yd7pnpLgB0Y+u+MlUZr+5IvIXQ9XGPQlFiezX+P/DG4cWsVyQHiW1GKSm0v0mNBYehLs+c5KtiIPZawk2yvBtt5Ww1NjTQj6WhGOvVfxFfskYS2vc3ga7jQJst2F3cD0ARAKtXTmBXOZgXrJrEGtJCTDDzIy5+98MxgplKa5ffMX5joixlK04YpKYYCK69FR+aZlNAz7lECGngXzuOaqVOBtxeB+WFbW6B9r2adTujAxYe7+MjxPQ42U0p5UF80hcJcN7rdVMaLmrMgLQM6sBOBSIj87ofXNRz0EHLQg6c1zwszbx3KM8S+wZXapTqMx6A5jxm8BksZoxBC+Duf77bDsfs/J95WAO9vdzyfEE9ON0RqJOnHehuW6yJk=
  file: build/libs/xlr-cloudbolt-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-cloudbolt-plugin
